Major package Update
nodertc/stun pull request #33
Opened 2021-08-12 20:08 UTC by theimo1221

Following some npm audits, it might be a good idea to update some of stuns packages.

I made sure all my changes resulted in valid unit test completion.

2021-08-15 08:13 UTC, theimo1221 commented
@olleolleolle Could you take a look over this?

2021-08-15 08:59 UTC, olleolleolle requested changes
Super-change! Thanks for taking the time to update the dependencies, that means a lot.

The linter did a good job of making uniform all the files.

The tests have carefully-composed arrays used as Buffer.from arguments, and it would be cool to build them in such a way that the line comments can be kept.

Perhaps like this, perhaps some other way, that lets the text remain on the same line as the value that it talks about.

```js
let input = []
input.push(0x00) // A null there.
```

2021-08-15 08:59 UTC, olleolleolle commented on test/attributes/stun-address-attribute.js
> +    0 /* Reserved */, 0x1 /* Family */, 0xf8, 0x24 /* Port */, 0xc0, 0xa8, 1, 2 /* IP */,
This is a linter removing the line comments, making it difficult for a reader to scan.

Can you find ways to build up the array (perhaps in more steps, perf does not matter in this test, but legibility will matter) that the linter will accept, and that lets the code keep the by-line comments?

2021-08-15 08:59 UTC, olleolleolle commented on test/attributes/stun-address-attribute.js
> +    0 /* Reserved */, 0x1 /* Family */, 0xf8, 0x24 /* Port */, 0xc0, 0xa8, 1, 2 /* IP */,
(Same here)

2021-08-15 08:59 UTC, olleolleolle commented on test/message/decode.js
> +    0, 0x01 /* Type */, 0, 12 /* Length */, 0x21, 0x12, 0xa4, 0x42 /* Cookie */, 0xd0, 0x05, 0x58,
(Same here in this file)

2021-08-15 08:59 UTC, olleolleolle commented on test/message/encode.js
> +    0, 0x01 /* Type */, 0, 12 /* Length */, 0x21, 0x12, 0xa4, 0x42 /* Cookie */, 0xd0, 0x05, 0x58,
(Same here in this file)

2021-08-15 15:06 UTC, theimo1221 commented
@olleolleolle Rhanks for the quick review! Following your suggestion I updated the PR.

2021-08-15 20:33 UTC, olleolleolle commented
(looks good to me!)

2021-08-15 21:26 UTC, theimo1221 commented
> (looks good to me!)

I thought you might have the necessary permissions to menge this PR and run a release...

Do you know how to reach one of the owners?

2021-08-17 17:34 UTC, theimo1221 commented
@reklatsmasters Could you look into this please

2021-11-29 14:28 UTC, reklatsmasters commented
A very controversial change, only brackets and bytes. Rejected.

2021-11-29 14:28 UTC, closed without merging

2021-11-29 16:52 UTC, theimo1221 commented
Hello @reklatsmasters,

I'm sorry but this PR doesn't just include brackets and bytes.
The main purpose are those package updates and afterwards the correctness in regards to the defined linting rules.

@olleolleolle am I missing something here?